### ISSUE TITLE
输出为文件message不显示

### ISSUE THREAD

**Issue by yllgl** [MyColorfulDays/jsonformatter#1]
我想将log同时输出到控制台和文件中，但是文件中的message不显示。
以下是我的代码：
`STRING_FORMAT = '''{
    "Levelname":       "levelname",
    "Filename":        "filename",
    "Lineno":          "lineno",
    "Asctime":         "asctime",
    "Message":         "%(message)s"
}'''
    root = logging.getLogger("bb.log")
    root.setLevel(logging.DEBUG)
    formatter = JsonFormatter(STRING_FORMAT)
    sh = logging.StreamHandler()
    sh.setFormatter(formatter)
    sh.setLevel(logging.DEBUG)
    th=logging.FileHandler("bb.log")
    th.setFormatter(formatter)
    th.setLevel(logging.DEBUG)
    root.addHandler(sh)
    root.addHandler(th)
    root.info("test format")`
![image](https://user-images.githubusercontent.com/23625282/61611916-aaf51500-ac8f-11e9-9c93-e27645dd459d.png)

**Comment by MyColorfulDays** [comment]
已修复，可以最新安装版本解决：
```shell
$ pip install jsonformatter --upgrade
```
或
```shell
$ git clone https://github.com/MyColorfulDays/jsonformatter.git
$ cd jsonformatter
$ python setup.py install
```
