### ISSUE TITLE
Do you have support for FastAPI

### ISSUE THREAD

**Issue by rpotnuru** [MyColorfulDays/jsonformatter#11]
Hello, Hope you are doing well !!

Do you have support for FastAPI ?

Thanks in advance.

**Comment by MyColorfulDays** [comment]
@rpotnuru Thank you.
I heard FastAPI  for the first time.

**Comment by rpotnuru** [comment]
thats okay, I figured out a way to work it out. thank you.

**Comment by mahenzon** [comment]
@rpotnuru hi! could you please share your solution for FastAPI?
