### ISSUE TITLE
Python 3.11 : AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

### ISSUE THREAD

**Issue by rpotnuru** [MyColorfulDays/jsonformatter#16]
Hello,

Getting below error when using with python version 3.11, do you have any solution or new release with the fix? Appreciate your help.
<module>
    sh.setFormatter(JsonFormatter(
                    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jsonformatter/jsonformatter.py", line 300, in __init__
    self.checkRecordCustomAttrs(self.record_custom_attrs)
  File "/usr/local/lib/python3.11/site-packages/jsonformatter/jsonformatter.py", line 191, in checkRecordCustomAttrs
    inspect.getargspec)(func)
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

**Comment by rpotnuru** [comment]
Here is the PR https://github.com/MyColorfulDays/jsonformatter/pull/17, pls see if this helps.

**Comment by MyColorfulDays** [comment]
@rpotnuru  This bug was fixed. Please use this command to fix it.
```shell
$ pip install jsonformatter --upgrade
```
or
```shell
$ git clone https://github.com/MyColorfulDays/jsonformatter.git
$ cd jsonformatter
$ python setup.py install
```
