### ISSUE TITLE
Can we have an option to disable wrapping dictionary messages as strings?

### ISSUE THREAD

**Issue by kuba-lilz** [MyColorfulDays/jsonformatter#8]
Currently if I use jsonformatter and try to log a message that is a dictionary, it wraps it into a string, e.g.:

```python
    logger.info({
        "data": "some text"
    })
```

results in (skipping other logging info)
```
{
	"message": "{'data': 'some text'}"
}
```

Is there any reason why formatter needs to wrap dictionaries in strings?
Ideally I would like to get the output in format:
```
{
	"message": {"data":"some text"}
}
```

I was actually able to do get this output by tweaking
`jsonformatter/jsonformatter.py:317` in `setRecordMessage` function
from
```python
        if isinstance(record.msg, (int, long, float, bool, type(None))):
            # keep these types without quote when output
            record.message = record.msg
```
to
```python
        if isinstance(record.msg, (dict, int, long, float, bool, type(None))):
            # keep these types without quote when output
            record.message = record.msg
```
(just added dict to list of object classes that don't get cast to strings)

Is there a good reason not to offer this option? Could we have it added as e.g. handler argument?

**Comment by kuba-lilz** [comment]
Playing a bit I see that some mixtures of keys that are valid python (e.g. some strings, some integers) seem to break when creating messages. Personally I think that's fine if not wrapping messages is an optional behavior and documentation highlights problematic corner cases, since core value from having dictionary message in json format rather than string - and thus being able to parse it as json - is very high.

**Comment by MyColorfulDays** [comment]
@kuba-lilz I had considered add a optional keyword argument `keep_iterator_types` to prevent some `Iterator Types` message convert to string, such as `dict`, `list`, `tuple`, but if it's a circular reference obj:
```python
import logging

from jsonformatter import JsonFormatter

sh = logging.StreamHandler()
sh.setFormatter(JsonFormatter())
sh.setLevel(logging.INFO)
logger = logging.getLogger('json_logger')
logger.setLevel(logging.INFO)
logger.addHandler(sh)

webs = {'foo': {}}
owners = {'bar': {}}
webs['foo']['owner'] = owners['bar']
owners['bar']['web'] = webs['foo']

logger.info(webs)

```
core:
```python
json.dumps({
    'message': webs
})
```
This will cause:
```shell
ValueError: Circular reference detected
```
But convert it to string, it can output.
core:
```python
josn.dumps({
    'message': st(rwebs)
})
```
output:
```shell
{"levelname": "INFO", "name": "json_logger", "message": "{'foo': {'owner': {'web': {...}}}}"}
```

**Comment by kuba-lilz** [comment]
Thank you for your reply.
Looks like I hadn't thought this out as well as you did, I didn't consider such corner cases at all ^^;

How about trying to emit with original object and falling back to string on failure? Some drawbacks of this approach you would prefer to avoid?

```python
try:

	emit(data)

except ValueError:

	emit(str(data))
```

**Comment by MyColorfulDays** [comment]
@kuba-lilz May I know why you want output nest log?
If you think it's necessarily and the probability of circular reference occurrence is very low, you can try this:
```python
import logging

from jsonformatter import basicConfig

basicConfig(
    level=logging.INFO,
    format="""{"levelname": "levelname", "name": "name", "message": "msg"}"""
)
logging.info({'data': {'key1': 'val1s'}})
```
output:
```shell
{"levelname": "INFO", "name": "root", "message": {"data": {"key1": "key2"}}}
```
Becase the attribute `msg` of `LogRecord`  stored the original value passed to logger.

**Comment by kuba-lilz** [comment]
So one situation where I use nested dictionaries for logging is verbose logs for web server endpoints processing, e.g. something like:

```python
    data = {
        "request": {
            "args": {
                "first": "this",
                "second": "that"
            },
            "method": "GET",
            "endpoint": "/my/endpoint",
            "user_agent": "firefox"
        },
        "response": {
                "status": 200,
                "body_size": 15,
                "processing_time_in_ms": 50
            }
    }

    logger.warning(data)
```

Playing with basicConfig would overwrite how root logger works, right?
I'm working with a large application that has a few loggers from different components, so a solution that affects only selected logger would be great.

This is how I configure logger now (this looks a bit artificial, because I cut out custom code that's not relevant to the issue at hand):
```python
    custom_record_format = collections.OrderedDict([
        ("message", "message"),
    ])

    formatter = jsonformatter.JsonFormatter(
        fmt=custom_record_format,
        ensure_ascii=False,
        sort_keys=True)
```

and the output looks like this:

```js
{"message": "{'request': {'args': {'first': 'this', 'second': 'that'}, 'method': 'GET', 'endpoint': '/my/endpoint', 'user_agent': 'firefox'}, 'response': {'status': 200, 'body_size': 15, 'processing_time_in_ms': 50}}"}
```

This isn't too bad, but it makes parsing logs a bit harder than if message value wasn't wrapped in a string.
If message value was a string, then logging services that parse json (e.g. loggly) let me select e.g. status with simple  `message.response.status`. 
Above won't work if message value is wrapped in a string.

I appreciate what I'm asking for is a corner case, and you might not be interested in supporting it.
Just hoping a sensible solution exists or can be easily added ^^;

**Comment by MyColorfulDays** [comment]
@kuba-lilz Yes, `basicConfig` is a shortcut for setting `root` logger.
If you want set a special logger, the full code:
```python
import collections
import logging

from jsonformatter import JsonFormatter

FROMAT = collections.OrderedDict([
    ("message", "msg"),
])

endpoint_logger = logging.getLogger('endpoint_logger')
endpoint_logger.setLevel(logging.INFO)

formatter = JsonFormatter(
    FROMAT,
    ensure_ascii=False,
    sort_keys=True
)

sh = logging.StreamHandler()
sh.setFormatter(formatter)
sh.setLevel(logging.INFO)

endpoint_logger.addHandler(sh)

endpoint_logger.info({
    "request": {
        "args": {
            "first": "this",
            "second": "that"
        },
        "method": "GET",
        "endpoint": "/my/endpoint",
        "user_agent": "firefox"
    },
    "response": {
        "status": 200,
        "body_size": 15,
        "processing_time_in_ms": 50
    }
})

```
output:
```shell
{"message": {"request": {"args": {"first": "this", "second": "that"}, "endpoint": "/my/endpoint", "method": "GET", "user_agent": "firefox"}, "response": {"body_size": 15, "processing_time_in_ms": 50, "status": 200}}}
```

**Comment by kuba-lilz** [comment]
O, that works like a charm, thank you!
