### ISSUE TITLE
Can we have the log output as a nested json

### ISSUE THREAD

**Issue by rpotnuru** [MyColorfulDays/jsonformatter#9]
Thank you for the work, I am looking for some more help here.

I want to print my log in a nested json format, is it possible? I am trying to publish my logs to elasticsearch.

Example log:

{
  "timestamp": "2021-04-01 14:37:37,877",
  "logType": "APP",
  "type": "log",
  "level": "ERROR",
  "message": "Api Failure",
  **"application": {
    "name": "my application",
    "env": "production"
  }**
}
 
Appreciate your help in this regrad.
Thanks, Ravi.

**Comment by MyColorfulDays** [comment]
@rpotnuru The `application` is a custom attribute, so, you should pass `record_custom_attrs`.
If you want `message` output nested json, refer to this [Can we have an option to disable wrapping dictionary messages as strings?](https://github.com/MyColorfulDays/jsonformatter/issues/8#issuecomment-758443970)
```python
import collections
import logging

from jsonformatter import JsonFormatter


formatter = JsonFormatter(
    collections.OrderedDict([
        ('timestamp', 'asctime'),
        ("logType", "APP"),
        ("type", "log"),
        ("message", "message"),
        ('application', 'application')
    ]),
    ensure_ascii=False,
    # sort_keys=True,
    record_custom_attrs={
        'application': lambda: collections.OrderedDict([
            ("name", "my application"),
            ("env", "production")
        ])
    }
)

sh = logging.StreamHandler()
sh.setFormatter(formatter)
sh.setLevel(logging.INFO)

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
logger.addHandler(sh)

logger.error('Api Failure')

```

**Comment by rpotnuru** [comment]
thank you for a quick response @MyColorfulDays , will give it a try.

**Comment by MyColorfulDays** [comment]
@rpotnuru Dose it work?
If it is, I will close it, and if you think the code is useful, thank you for star⭐ it.

**Comment by rpotnuru** [comment]
this helped and yes the code did helped me to get what I want. Appreciate your contribution.

**Comment by rpotnuru** [comment]
I gave my star @MyColorfulDays :-) and thank you.

One last question: Please see attached image of my logs, why I am seeing the default log also getting printed in addition to my formatted log, I may be missing something here.
<img width="611" alt="Screen Shot 2021-04-02 at 9 58 02 AM" src="https://user-images.githubusercontent.com/3529965/113436627-eb2ff480-9399-11eb-8460-a4287f76bcc5.png">

Appreciate your help.

**Comment by MyColorfulDays** [comment]
@rpotnuru It seems the `root` logger has two `handlers`.
Can you paste your logger config code?

**Comment by rpotnuru** [comment]
Here is the code:   
 formatter = JsonFormatter(
        RECORD_CUSTOM_FORMAT,
        record_custom_attrs=RECORD_CUSTOM_ATTRS,
        ensure_ascii=False
    )
    sh = logging.StreamHandler()
    sh.setFormatter(formatter)
    sh.setLevel(logging.INFO)

    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)
    logger.addHandler(sh)

**Comment by rpotnuru** [comment]
RECORD_CUSTOM_FORMAT = OrderedDict([
    # custom record attributes start
    ("timestamp", "timestamp"),
    ("application", "application"),
    ("environment", "environment"),
    ("schemaVersion", "schemaVersion"),
    ("logType", "logType"),
    ("type", "type"),
    # custom record attributes end
    ("level", "levelname"),
    ("message", "message"),
])

RECORD_CUSTOM_ATTRS = {
    # no parameters
    'logType': lambda: "TEST",
    'type': lambda: "log",
    'application': lambda: collections.OrderedDict([
        ("name", get_env_var("APP_NAME", "abc")),
        ("namespace", get_env_var("OPENSHIFT_BUILD_NAMESPACE", "xyz")),
        ("carId", get_env_var("APPID", "12345"))
    ]),
    'environment': lambda: collections.OrderedDict([
        ("name", get_env_var("ENV", "dev")),
        ("host", socket.gethostname()),
        ("cluster", socket.gethostname())
    ]),
    'schemaVersion': lambda: "1.0.0",
    'timestamp': lambda: datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
}

**Comment by MyColorfulDays** [comment]
@rpotnuru 
This is the full code for your reference. 
Please note `basicConfig(level=logging.INFO)` and `logger.propagate = False`.
If the problem persists, please show me the full code and full output, or refer to the offical doc 
<https://docs.python.org/3/howto/logging.html#logging-basic-tutorial>
```python
import collections
import logging
import socket
from collections import OrderedDict
from os import getenv as get_env_var
from datetime import datetime, timezone

from jsonformatter import JsonFormatter, basicConfig

# This is set `root` logger can output `INFO` level log.
basicConfig(level=logging.INFO)

RECORD_CUSTOM_FORMAT = OrderedDict([
    # custom record attributes start
    ("timestamp", "timestamp"),
    ("application", "application"),
    ("environment", "environment"),
    ("schemaVersion", "schemaVersion"),
    ("logType", "logType"),
    ("type", "type"),
    # custom record attributes end
    ("level", "levelname"),
    ("message", "message"),
])

RECORD_CUSTOM_ATTRS = {
    # no parameters
    'logType': lambda: "TEST",
    'type': lambda: "log",
    'application': lambda: collections.OrderedDict([
        ("name", get_env_var("APP_NAME", "abc")),
        ("namespace", get_env_var("OPENSHIFT_BUILD_NAMESPACE", "xyz")),
        ("carId", get_env_var("APPID", "12345"))
    ]),
    'environment': lambda: collections.OrderedDict([
        ("name", get_env_var("ENV", "dev")),
        ("host", socket.gethostname()),
        ("cluster", socket.gethostname())
    ]),
    'schemaVersion': lambda: "1.0.0",
    'timestamp': lambda: datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
}

formatter = JsonFormatter(
    RECORD_CUSTOM_FORMAT,
    record_custom_attrs=RECORD_CUSTOM_ATTRS,
    ensure_ascii=False
)
sh = logging.StreamHandler()
sh.setFormatter(formatter)
sh.setLevel(logging.INFO)

logger = logging.getLogger(__name__)
# This is prevent logger `propagate` to `root` logger.
logger.propagate = False

logger.setLevel(logging.INFO)
logger.addHandler(sh)
logger.info('testing')
logger.info(logger.handlers)

# Get `root` logger and output its handlers.
root_logger = logging.getLogger()
root_logger.info(root_logger.handlers)
```

**Comment by rpotnuru** [comment]
sure.. thank you @MyColorfulDays .

**Comment by rpotnuru** [comment]
Perfect, it is working now @MyColorfulDays , logger.propagate = False did the trick. Sorry for the miss.

**Comment by rpotnuru** [comment]
sorry about the dumb question.. I should have done some research.

**Comment by MyColorfulDays** [comment]
@rpotnuru You're welcome
